### ISSUE TITLE
Will there be image upload feature so I don't have to user jQuery SDK?

### ISSUE THREAD

**Issue by paurakhsharma** [cloudinary/cloudinary-vue#10]
First of all, thank for this project.

As I saw in the documentation that `cloudinary-vue` doesn't support
image upload and I have to use `jQuery` or `Pure JS` for uploading 
an image from a client site.

Can we expect similar image upload feature in this library like in `jQuery`?
Thanks.

**Comment by arturkulig** [comment]
We will be adding [Cloudinary Upload Widget](https://cloudinary.com/documentation/upload_widget) <-> Vue integration in this SDK soon.

**Comment by paurakhsharma** [comment]
Thanks for the quick replay

**Comment by andrewlamyw** [comment]
> We will be adding [Cloudinary Upload Widget](https://cloudinary.com/documentation/upload_widget) <-> Vue integration in this SDK soon.

Is there an estimated time?

**Comment by unr** [comment]
Any update on this @arturkulig ?

**Comment by rebeccapeltz** [comment]
We have a feature request logged for this. In the meantime, you can write an upload component using the Upload API: [Creating a Vue.js Application for Uploading Assets to Cloudinary](https://support.cloudinary.com/hc/en-us/articles/360011139699-Creating-a-Vue-js-Application-for-Uploading-Assets-to-Cloudinary), or you can wrap a Cloudinary widget in a framework component.  This example wraps a video player widget but the technique can apply to any widget.  Add the Cloudinary widget script and jQuery to the src/index.html and wrap the script in a component: [Wrapping a Video Player Widget in Vue.js](https://github.com/rebeccapeltz/vue-cl-test).

**Comment by unr** [comment]
Perfect answer for now, thank you @rebeccapeltz :)

(That's basically how I'm using it currently, was curious after seeing this issue)

**Comment by rebeccapeltz** [comment]
Update on this: The feature is still on our roadmap but not scheduled.  Here is some sample code that will render the Upload Widget in Vue.js. https://codepen.io/rpeltz/pen/WNZKrNP
