### ISSUE TITLE
Require vue as peerDependency

### ISSUE THREAD

**Issue by jankal** [cloudinary/cloudinary-vue#101]
## Feature request for Cloudinary Vue SDK
Please specify vue as a peer-dependency of you package instead of a direct depedency and try to be more open about upper and lower version bounds of the vue package.
It's now the second time, this package dictates the vue version I can use. And that's annoying.

## Explain your use case
Every kind of usage in an environment where other packages and version constraints are involved.

## Describe the problem you’re trying to solve
see above.

## Do you have a proposed solution?
see above.

**Comment by roeeba** [comment]
Hi @jankal, Thank you for pointing this out. We've opened an internal ticket to our developers and we'll update once there is there's any progress.

**Comment by DerekAlanGilbert** [comment]
This is also an issue my team is facing. Thanks for taking care of it 👍

**Comment by patrick-tolosa** [comment]
Hey @briancbarrow , we've just released version 1.1.2 which should address this issue,
Please let us know if this solves your problem.

Regards,
Patrick

**Comment by patrick-tolosa** [comment]
I'm closing this issue as the fix is already available, if you encounter any more issues, feel free to open a new issue.

Thanks for reporting this
