### ISSUE TITLE
default-image not getting considered

### ISSUE THREAD

**Issue by diegopamio** [cloudinary/cloudinary-vue#103]
##  Describe the bug in a sentence or two.
The `default-image='<publicID>'` prop is not getting transformed into a `d_<publicID>` string in the url.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross-browser issues
[ ] UI/Performance - Display or performance issues
[X] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behavior
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
* Add a default-image prop  to either the `cdl-image` or a transformation element.
* Check the cloudinary URL for the given element.

## Error screenshots
N/A

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[ ] All

## Versions and Libraries (fill in the version numbers)
Vue Cloudinary SDK - 1.0.0
Vue - 2.0.0
VueCLI - N/A
Babel - 0.0.0
Webpack/Rollup/Other - 0.0.0
Node - 0.0.0
NPM - 0.0.0

## Config Files (Please paste the following files if possible)
Package.json
Webpack.config
Babelrc

## Repository
If possible, please provide a link to a reproducible repository

**Comment by patrick-tolosa** [comment]
Hey @diegopamio  - The Vue SDK doesn't have a `default-image` prop, can you please share a link to where you've seen this used?

**Comment by diegopamio** [comment]
I haven't, but I assumed that, if the Javascript core SDK has it, it should have it too (perhaps this should turn from bug to feature). Is there a way to achieve the desired results otherwise?

I assumed that if this was supported by cloudinary_js it should be available in different javascript libraries:
https://github.com/cloudinary/cloudinary_js/blob/b3dd7b6e71f4c0aa4ec4190d3356acc475f87d22/src/transformation.js#L633

**Comment by patrick-tolosa** [comment]
Hey @diegopamio 

The prop is available through `defaultImage`,

For example
```javascript
<cld-image cloudName="demo" publicId="sample" defaultImage="lala"></cld-image>
```
will generate `https://res.cloudinary.com/demo/image/upload/d_lala/sample`

**Comment by diegopamio** [comment]
Oh... I see I wasn't able to try with camelCase as my ESlint was complaining about it with: ESLint: Attribute 'defaultImage' must be hyphenated.(vue/attribute-hyphenation)

It worked!

Is that different than all other props like `public-id` that are hyphenated?

**Comment by patrick-tolosa** [comment]
As you mentioned, some of the attributes you can add to the Vue cld-image get cascaded down to our internal implementations.

Vue treats `props` and `attributes` differently. 
Since publicID is a prop, you can pass it as both `public-id` and `publicId` and Vue will handle the change automatically.

`defaultImage` is not a property of cld-image, but just a custom attribute we collect and pass down. Because of that it does not get the same treatment, and Vue will not turn `default-image` into `defaultImage`

**Comment by diegopamio** [comment]
Great explanation, thanks!
