### ISSUE TITLE
Remove core-js as dependency

### ISSUE THREAD

**Issue by jankal** [cloudinary/cloudinary-vue#105]
## Feature request for Cloudinary Vue SDK
If possible, removing core-js from cloudinary-vue's dependencies would really shrik the dependency graph of projects working with it. Core-js seems to not being used in the code. The only files I can find relations to core-js are package.json and package-loc.json

## Describe the problem you’re trying to solve
This feature will help me to reduce the size of e.g. my docker-images.

**Comment by IamTheHttp** [comment]
Hey @jankal ,

Thanks for your suggestion, these are always very welcomed! 

Core-JS is actually used quite heavily in the build output of this library.
You won't see a reference in the codebase, but when the project is built, you'll see some interesting lines in the dist files

For example:
```javascript
module.exports = require("core-js/modules/es6.symbol");
```

If core-js is not present and you try to import this library, you'll run into some errors of missing files.
Ideally, core-js should be a peer dependency, however we've had problems in the past where a user was using a different version of core-js for his own needs, and he was unable to install the version needed by this SDK.

The lesser evil is to incorporate it as part of our package.

**Comment by patrick-tolosa** [comment]
Hey @jankal ,

Thanks for your suggestion, these are always very welcomed!

Core-JS is actually used quite heavily in the build output of this library.
You won't see a reference in the codebase, but when the project is built, you'll see some interesting lines in the dist files

For example:
```javascript
module.exports = require("core-js/modules/es6.symbol");
```

If core-js is not present and you try to import this library, you'll run into some errors of missing files.
Ideally, core-js should be a peer dependency, however we've had problems in the past where a user was using a different version of core-js for his own needs, and he was unable to install the version needed by this SDK.

The lesser evil is to incorporate it as part of our package.

**Comment by jankal** [comment]
Hi @patrick-tolosa 

I see the reason for this. When there are users out there facig issues when it's not part of the package, you should have it included and leave it as is for now.
It's just another thing you have to maintain the version number for.

**Comment by Marvin1003** [comment]
How is the process of including 

> Hey @jankal ,
> 
> Thanks for your suggestion, these are always very welcomed!
> 
> Core-JS is actually used quite heavily in the build output of this library.
> You won't see a reference in the codebase, but when the project is built, you'll see some interesting lines in the dist files
> 
> For example:
> 
> ```js
> module.exports = require("core-js/modules/es6.symbol");
> ```
> 
> If core-js is not present and you try to import this library, you'll run into some errors of missing files.
> Ideally, core-js should be a peer dependency, however we've had problems in the past where a user was using a different version of core-js for his own needs, and he was unable to install the version needed by this SDK.
> 
> The lesser evil is to incorporate it as part of our package.

**Comment by Marvin1003** [comment]
How is the process of defining _core-js_ as a peer dependency? It should be the decision of the host that includes this package, if polyfills are needed based on his targeted browsermatrix. As _cloudinary-core_ is already a very tall package, dropping _core-js_ would be at least a small win.
> Hey @jankal ,
> 
> Thanks for your suggestion, these are always very welcomed!
> 
> Core-JS is actually used quite heavily in the build output of this library.
> You won't see a reference in the codebase, but when the project is built, you'll see some interesting lines in the dist files
> 
> For example:
> 
> ```js
> module.exports = require("core-js/modules/es6.symbol");
> ```
> 
> If core-js is not present and you try to import this library, you'll run into some errors of missing files.
> Ideally, core-js should be a peer dependency, however we've had problems in the past where a user was using a different version of core-js for his own needs, and he was unable to install the version needed by this SDK.
> 
> The lesser evil is to incorporate it as part of our package.

**Comment by patrick-tolosa** [comment]
That is on our mind, however, this will be a breaking change to existing users.
Since we're already working on a new alternative to the existing JS libraries, we'd like to avoid releasing a major for Vue, only to release a whole new library in a few weeks.
