### ISSUE TITLE
"unknown cloud_name" with Nuxt

### ISSUE THREAD

**Issue by ascottmccauley** [cloudinary/cloudinary-vue#11]
I can't seem to get the cloud_name to reference globally across the entire Nuxt app.
I have added the following plugin to the *nuxt.config.js* but receive the notice **Unknown cloud_name** . 
Adding the cloudname to the template component works: `<cld-image cloudName="demo" publicId="sample" />` but shouldn't I be able to set that globally?

```javascript
// ~/plugins/cloudinary.js
import Vue from 'vue'
import Cloudinary from 'cloudinary-vue'

Vue.use(Cloudinary, {
  configuration: {
    cloudName: 'demo',
  }
})
```

```vue
// ~/pages/index.vue
<template>
  <main>
    <h1>Cloudinary Test</h1>
    <cld-image publicId="sample" />
  </main>
</template>

<script>
export default {}
</script>
```

**Comment by strausr** [comment]
@ascottmccauley We're unable to reproduce this on our end. Can you please share with us a live example?

**Comment by ascottmccauley** [comment]
Sorry, I can't replicate it now either. 
Not sure what changed overnight.

**Comment by macguirerintoul** [comment]
Seeing this with Gridsome. Example: https://github.com/macguirerintoul/macguire.me/commit/845c46241292ce1e402bba88cc44c74fe83a9ecd

Checkout `dev` branch @ 845c462, run `gridsome build`

**Comment by patrick-tolosa** [comment]
Hey @macguirerintoul  

It has been a year since this issue has been closed,
Can you please file a new issue so we can assist? 

I tried using the instructions you provided but was unable to reproduce.
Please create a new issue with as much information as possible.
