### ISSUE TITLE
What is the status of Vue 3 support now that it is stable.

### ISSUE THREAD

**Issue by RitikPatni** [cloudinary/cloudinary-vue#111]
## Feature request for Cloudinary Vue SDK
…(If your feature is for other SDKs, please request them there)

## Explain your use case
I'm upgrading my application to Vue 3 and the current package is giving me error.

## Describe the problem you’re trying to solve
This is the error I'm getting and the component which is using this doesn't render after this

```
Uncaught (in promise) TypeError: can't access property "_c", _vm._self is undefined
    CldImagevue_type_template_id_621bb132_render Cloudinary.umd.js:749
    renderComponentRoot runtime-core.esm-bundler.js:696
    componentEffect runtime-core.esm-bundler.js:4035
    reactiveEffect reactivity.esm-bundler.js:42
    effect reactivity.esm-bundler.js:17
    setupRenderEffect runtime-core.esm-bundler.js:4018
    mountComponent runtime-core.esm-bundler.js:3976
    processComponent runtime-core.esm-bundler.js:3936
    patch runtime-core.esm-bundler.js:3547
    mountChildren runtime-core.esm-bundler.js:3736
    mountElement runtime-core.esm-bundler.js:3659
    processElement runtime-core.esm-bundler.js:3631
    patch runtime-core.esm-bundler.js:3544
    componentEffect runtime-core.esm-bundler.js:4053
    reactiveEffect reactivity.esm-bundler.js:42
    effect reactivity.esm-bundler.js:17
    setupRenderEffect runtime-core.esm-bundler.js:4018
    mountComponent runtime-core.esm-bundler.js:3976
    processComponent runtime-core.esm-bundler.js:3936
    patch runtime-core.esm-bundler.js:3547
    mountChildren runtime-core.esm-bundler.js:3736
    processFragment runtime-core.esm-bundler.js:3899
    patch runtime-core.esm-bundler.js:3540
    mountChildren runtime-core.esm-bundler.js:3736
    mountElement runtime-core.esm-bundler.js:3659
    processElement runtime-core.esm-bundler.js:3631
    patch runtime-core.esm-bundler.js:3544
    patchBlockChildren runtime-core.esm-bundler.js:3855
    patchElement runtime-core.esm-bundler.js:3816
    processElement runtime-core.esm-bundler.js:3634
    patch runtime-core.esm-bundler.js:3544
    componentEffect runtime-core.esm-bundler.js:4117
    reactiveEffect reactivity.esm-bundler.js:42
    callWithErrorHandling runtime-core.esm-bundler.js:154
    flushJobs runtime-core.esm-bundler.js:364
    promise callback*queueFlush runtime-core.esm-bundler.js:264
    queueJob runtime-core.esm-bundler.js:258
    run reactivity.esm-bundler.js:183
    trigger reactivity.esm-bundler.js:189
    set reactivity.esm-bundler.js:291
    set runtime-core.esm-bundler.js:5960
    fetchMarketplaces SelectMarketplace.vue:106
```

## Do you have a proposed solution?
No

**Comment by patrick-tolosa** [comment]
Hey @RitikPatni 

This SDK does not support Vue 3.
Unfortunately, there's no migration path to Vue3, and the entire library needs to change to support it.

If we'll offer a Vue3 solution, it'll most likely be in its own repository.

**Comment by RitikPatni** [comment]
@patrick-tolosa Are there any plans for it in near future.

**Comment by patrick-tolosa** [comment]
We're currently working on a new version for the VueJS SDK, however, I'm not sure it will include support for Vue 3(it's too early to say).

We feel Vue3, while officially released, is not mature enough and doesn't have enough community support to merit its own SDK.
This is constantly being re-evaluated.

I'm keeping this issue open to see if other users have the same need.

**Comment by RitikPatni** [comment]
Thanks @patrick-tolosa

**Comment by soderkr** [comment]
Hi @patrick-tolosa what is the status of this? Asking as the lack of support for Vue 3 is a blocker in our project.

**Comment by patrick-tolosa** [comment]
Hey @soderkr  - No updates on this front, we'll update when we decide to tackle Vue 3 as an SDK.
this is not just Vue 3 support, but a whole new SDK as the internals are completely different.

**Comment by frontseatv** [comment]
Hi @patrick-tolosa, is there a workaround for Vue 3 developers we can use?

**Comment by brandiqa** [comment]
Hi @patrick-tolosa, is there a workaround that Vue 3 developers can use in the meantime?

**Comment by patrick-tolosa** [comment]
Hey @brandiqa  - No updates for Vue 3 yet.

**Comment by namsir** [comment]
> Hi @patrick-tolosa, is there a workaround that Vue 3 developers can use in the meantime?

create your own component with their js sdk.

**Comment by awacode21** [comment]
we are now in 2022 and Vue 3 is there for a while now. What's your current state? No Vue 3 support is a clear blocker for me to use cloudinary. Feels quite outdated. Competitors are faster on this.

**Comment by patrick-tolosa** [comment]
@awacode21 Thanks for pinging on this.
It's still on our roadmap, but this should not be a blocker by any means for Cloudinary.

Using the latest JS library (https://github.com/cloudinary/js-url-gen) which handles URL-generation exclusively, it's rather trivial writing your vue bindings on top of it. (Note that it's usage is very different from this Vue library)

Vue 3 support would probably be part of our next-gen client libraries (https://github.com/cloudinary/frontend-frameworks) - we already support React and Angular and Vue, as mentioned, is on the roadmap.


For most projects, the URL-generation library is more than enough and the UI features of responsive and lazy-load will be coming in a Vue 3 compatible way in the future.

**Comment by Sjoerd82** [comment]
2023 here... could Cloudinary give a ballpark estimate on Vue3 support? Much appreciated! 👍 👍

**Comment by tamaracloudinary** [comment]
Hi @Sjoerd82, Cloudinary supports Vue3, here is the documentation:
https://cloudinary.com/documentation/vue_integration

**Comment by Sjoerd82** [comment]
Great! My mistake, I tought that [cloudinary-vue](https://www.npmjs.com/package/cloudinary-vue) was @cloudinary/vue. Digging deeper, indeed Vue3 is suppprted. I just installed the module and will try it out soon. Thanks for the reply.

**Comment by tamaracloudinary** [comment]
Hi @Sjoerd82 no worries, I will mark this ticket as solved now but if there are any follow-up questions, please feel free to reach out with any further issues or questions you have using our support center: http://support.cloudinary.com.
