### ISSUE TITLE
dpr: auto no longer works when `responsive` is set

### ISSUE THREAD

**Issue by syropian** [cloudinary/cloudinary-vue#137]
## Describe the bug in a sentence or two.

Since #122, having both `dpr="auto"` and `responsive` attributes on an image results in blurry images for devices with a DPR higher than 1. Rolling back to `v1.1.2` fixed the issue for me.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross-browser issues
[x] UI/Performance - Display or performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behavior
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
- Add a `CldImage` element with `responsive` and `dpr="auto"`, view on a device with a DPR > 1 (most mobile phones these days)

## Versions and Libraries (fill in the version numbers)
Vue Cloudinary SDK - >= 1.2.0

**Comment by patrick-tolosa** [comment]
Thanks for reporting this issue,

We've already merged a fix in #138  we'll release a new version within a week or two.

**Comment by syropian** [comment]
Beautiful, thanks so much!

**Comment by patrick-tolosa** [comment]
@syropian - We've just released version 1.2.2 that should resolve this issue,
Please let us know if you're still having issues. (Closing this issue for now)

**Comment by syropian** [comment]
Works great @patrick-tolosa! Very much appreciated ❤️
