### ISSUE TITLE
Autoloading not working in chrome

### ISSUE THREAD

**Issue by blaadje** [cloudinary/cloudinary-vue#140]
## Describe the bug in a sentence or two.
Hi, with the new `1.2.0` version (`1.2.2` as well)
- I can't make the **video** autoloading working.
- Poster won't load the correct ones (loading a .gif)

## Issue Type (Can be multiple)
[x] Behaviour - Functions aren’t working as expected (Such as generate URL)

## Steps to reproduce

You can reproduce the issue in this pen https://codepen.io/blaadje/pen/GRmZXyr?editors=1010

## Browsers (if issue relates to UI, else ignore)
[x] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[ ] All

Let me know if I missed something. Thank you !

**Comment by victorli-cloudinary** [comment]
Hi there, thanks for reaching out to us! I'm checking in with our internal team to look into this for you. We'll update you as soon as we have findings to share.

**Comment by Vdeub-cloudinary** [comment]
Hi @blaadje,
The team is currently working on a fix and we hope to release it next week.
We will keep you posted on our progress.

**Comment by patrick-tolosa** [comment]
Hi @blaadje,

A PR Fixing it was merged and released under version `1.2.3`
I'm closing the issue, but if you're still having problems please reply here or open a new issue.

**Comment by blaadje** [comment]
Okay ! Thank you for your reactivity !
