### ISSUE TITLE
Cloudinary-vue not working in Vue 3

### ISSUE THREAD

**Issue by dajpes** [cloudinary/cloudinary-vue#165]
## Bug report for Cloudinary Vue SDK
Using cloudinary-vue 1.2.4, I get the following error:

"TypeError: h is not a function"

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross-browser issues
[ ] UI/Performance - Display or performance issues
[x] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behavior
[x] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
Just go to the following repo:

https://stackblitz.com/edit/vue-ftvhtr?file=src/App.vue

## Versions and Libraries (fill in the version numbers)
Vue Cloudinary SDK - 1.2.4
Vue - 3.2.26
VueCLI - 0.0.0 / N/A
Babel - 0.0.0
Webpack/Rollup/Other - 0.0.0
Node - 0.0.0
NPM - 0.0.0

**Comment by dannyv-cloudinary** [comment]
Hi @dajpes.

Thanks for raising this with us. Currently, our SDK doesn't support Vue 3. We're working on a new version which we hope to release in the not too distant future, however for now, you will need to use Vue 2 in order to use our SDK.

I hope this helps.

Thanks,
-Danny

**Comment by SebiBasti** [comment]
@dannyv-cloudinary Are there any updates about Vue 3 support?

**Comment by dannyv-cloudinary** [comment]
Hey @SebiBasti. Vue 3 is indeed supported now! Please see
https://github.com/cloudinary/frontend-frameworks/tree/master/packages/vue

**Comment by SebiBasti** [comment]
@dannyv-cloudinary Neat! 🚀
