### ISSUE TITLE
responsive="width" doesn't return a larger image when the page is resized

### ISSUE THREAD

**Issue by zaros-systems** [cloudinary/cloudinary-vue#17]
I'm having problems with responsive. 

As expected, when my image container width is small, responsive="width" returns a small image.
As expected, when my image container width is large, responsive="width" returns a large image.

However, if my initial image container width is small and I then increase the image container's width, I do not receive a larger image as I would expect. Instead, the small image gets stretched and blurred, as a new image with a larger width is not sent.

This is a problem that will affect mobile and tablet users, as if the device is tilted from profile to landscape, the images will no longer be sharp. It will also be a problem for users that open the site in a small window and then maximise the window.

---

We are also experiencing an issue where both the original high resolution image is sent, alongside the resized image that is created by responsive. I have attached an image showing this in the network tab. This duplicate original resolution image is not displayed or used anywhere on the page.

Thank you.

![clear large container width](https://user-images.githubusercontent.com/50753883/57955772-a5c1c580-78ee-11e9-8491-027651947448.PNG)
![small container width](https://user-images.githubusercontent.com/50753883/57955773-a5c1c580-78ee-11e9-92ae-c269d6e652e1.PNG)
![stretched blurry large container width](https://user-images.githubusercontent.com/50753883/57955774-a65a5c00-78ee-11e9-9431-b3d2910c9312.PNG)
![1](https://user-images.githubusercontent.com/50753883/57955775-a65a5c00-78ee-11e9-9073-d65dd86a1371.PNG)

**Comment by arturkulig** [comment]
Hi! Thank you for posting this.
As you can see - I've created a fix for a second issue you have mentioned.
About the first however: I can see it in a released version and I don't in dev builds, so I assume the fix is already awaiting for release. I will notify you when that happens, so we can figure out where we are with this.
