### ISSUE TITLE
Missing required prop: "publicId" on cld-video

### ISSUE THREAD

**Issue by RicLeP** [cloudinary/cloudinary-vue#22]
I keep getting missing publicId despite setting one.

```
// app.js
...

import Cloudinary from "cloudinary-vue";

window.Vue = require('vue');

Vue.use(Cloudinary, {
	configuration: {
		cloudName: 'xxxxx',
	},
	components: ['CldVideo']
});

...

```

And in my HTML

```
<cld-video publicId="xxxxx"></cld-video>
```

Everything looks correct according to the documentation but the publicId prop isn’t found.

**Comment by arturkulig** [comment]
That is quite a serious issue, but I'm not sure where to seek for the cause.
Can you first try to create a demoable reproduction of the issue? Just this does not seem to be the issue - maybe there is something more in your project that is causing that.

You can 
[![Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x99znj8194?fontsize=14)
or create your own publicly available repo.

**Comment by mayashavin** [comment]
@RicLeP Does this issue still happen? Can you provide us more information such as screenshot of console log? Your settings? Thanks
