### ISSUE TITLE
Adding 'responsive' prop doesn't render properly

### ISSUE THREAD

**Issue by macguirerintoul** [cloudinary/cloudinary-vue#23]
Hi there,

Thanks for creating this. I'm having trouble getting responsive images set up as described in the documentation. `<CldImage>` works fine with all other props (i.e. `dpr="auto"`, `width="auto"`), but when I add `responsive` as shown [here](https://cloudinary.com/documentation/vue_image_manipulation#responsive_image_settings), the component doesn't render properly — all I get in the DOM is `<img class="cld-image">` with an empty comment inside, as shown in the screenshot.

![Screen Shot 2019-08-05 at 1 09 38 PM](https://user-images.githubusercontent.com/18323154/62492076-76e71d00-b782-11e9-9d4b-fea18c60dab0.png)

When I remove `responsive`, everything works as expected.

My markup:
```
<CldImage
    responsive
    dpr="auto"
    width="auto"
    crop="scale"
    :alt="alt"
    :public-id="cloudinaryID"
  >
    <CldTransformation quality="auto" fetch-format="auto" />
  </CldImage>
```

**Comment by brian-cloudinary** [comment]
Thanks for pointing this out. Please use `responsive="width"` in the meantime.
