### ISSUE TITLE
Split CldPicture and CldSource to separate PR

### ISSUE THREAD

**Issue by mayashavin** [cloudinary/cloudinary-vue#25]

**Comment by arturkulig** [comment]
Done.

---

There are two options: Either creating a new task or change a title of this one to
_~Split CldPicture and CldSource to separate PR~ Redesign and reimplement CldPicture_

**Comment by arturkulig** [comment]
@mayashavin 
Done
https://github.com/cloudinary/cloudinary-vue/pull/33
