### ISSUE TITLE
Error using cld-image after upgrading from version 1.0.0-beta2 to 1.0.0-beta3

### ISSUE THREAD

**Issue by andrewlamyw** [cloudinary/cloudinary-vue#50]
What are the breaking changes introduced from version 1.0.0-beta2 to 1.0.0-beta3?

**Comment by arturkulig** [comment]
There should be none. In case you have noticed an unexpected behavior, please write down what were you expecting and how that expectation was not fulfilled.
A demo of that failure will be much appreciated!
