### ISSUE TITLE
[Documentation] Update Release note for Beta 3 release

### ISSUE THREAD

**Issue by mayashavin** [cloudinary/cloudinary-vue#51]
<img width="996" alt="Screen Shot 2019-11-06 at 14 22 02" src="https://user-images.githubusercontent.com/6650139/68297956-e1b93480-00a0-11ea-8536-d7eb454cfe06.png">
Current there is no description of what was changed. Need to be updated.

**Comment by arturkulig** [comment]
https://github.com/cloudinary/cloudinary-vue/releases/tag/1.0.0-beta3
