### ISSUE TITLE
[Suggestion] new prop: img-class

### ISSUE THREAD

**Issue by hellokvn** [cloudinary/cloudinary-vue#55]
**Like:**
`<cld-image publicId="img.public_id"  class="image" img-class="avatar" />`

**Result:**
```
<div class="cld-image image">
<img cloud-name="dxdqhh6rqt" flag="flag" src="http://res.cloudinary.com/..." class="avatar">
</div>
```

**Comment by shirlymanor** [comment]
Thank you for your feedback!
I'll forward it to our product team to consider adding it to our roadmap.

**Comment by mayashavin** [comment]
@hellokvn the next version all the classes passed to `cld-image` will apply to generated `img` tag. Hence we don't need `img-class`

Please pay attention that if you use `placeholder` or `CldPlaceholder`, there will be a wrapper class with class name `cld-image--wrapper` and this wrapper will also inherit classes passed. Generated `img` will have default class name `cld-image`.

Enhanced in #117

**Comment by ceilfors** [comment]
May I know when will this change be released?

**Comment by mayashavin** [comment]
@ceilfors this will be released shortly. Hopefully this or next week. Currently we are working on solving a problem related to corejs 2x build support. I will update you when it's out :)
