### ISSUE TITLE
Feature: Update wrapping element

### ISSUE THREAD

**Issue by avr** [cloudinary/cloudinary-vue#57]
I'd like to be able to control the wrapping element - aka replace `<div class="cld-image">` with `<figure class="cld-image">`

This can be achieved by using a simple render function in CldImage.vue.  I have this working in a simple test - are you open to a PR?

Thanks!
avr

**Comment by mayashavin** [comment]
Hi @avr ,

Sound good. Please submit a PR and we will take a look :)

**Comment by patrick-tolosa** [comment]
@avr  I'm closing this due to time passed,
However, we're very open to new ideas and community PRs.
You're more than welcome to reopen this issue or submit a PR.
