### ISSUE TITLE
[Bug] Transformation failed to work with transformation nested in transformation

### ISSUE THREAD

**Issue by mayashavin** [cloudinary/cloudinary-vue#61]
Using Cld-Transformation with nested transformation doesn't rendered correctly.

**Comment by asisayag2** [comment]
@mayashavin , can you give an example? 
What is the use-case of doing that?

**Comment by patrick-tolosa** [comment]
@mayashavin  - I'm closing this issue as the description is not clear and a lot of time has passed since this was opened.

If you can provide an example for this issue please re-open.
