### ISSUE TITLE
Module not found: Error: Can't resolve './components/CldContext/CldContext' 

### ISSUE THREAD

**Issue by shrestha2lt8** [cloudinary/cloudinary-vue#64]
ERROR in ./node_modules/cloudinary-vue/src/index.js
Module not found: Error: Can't resolve './components/CldContext/CldContext' in 'E:\Other\Project\Yeti\FILMD\Source\FILMD-Engine\FILMD.Web\node_modules\cloudinary-vue\src'
 @ ./node_modules/cloudinary-vue/src/index.js 2:0-60 10:83-93 14:0-18:2
 @ ./scripts/index.js
 @ multi ./scripts/index.js
ERROR in ./node_modules/cloudinary-vue/src/index.js
Module not found: Error: Can't resolve './components/CldImage/CldImage' in 'E:\Other\Project\Yeti\FILMD\Source\FILMD-Engine\FILMD.Web\node_modules\cloudinary-vue\src'
 @ ./node_modules/cloudinary-vue/src/index.js 3:0-54 10:95-103 14:0-18:2
 @ ./scripts/index.js
 @ multi ./scripts/index.js
ERROR in ./node_modules/cloudinary-vue/src/index.js
Module not found: Error: Can't resolve './components/CldTransformation/CldTransformation' in 'E:\Other\Project\Yeti\FILMD\Source\FILMD-Engine\FILMD.Web\node_modules\cloudinary-vue\src'
 @ ./node_modules/cloudinary-vue/src/index.js 6:0-81 10:115-132 14:0-18:2
 @ ./scripts/index.js
 @ multi ./scripts/index.js
ERROR in ./node_modules/cloudinary-vue/src/index.js
Module not found: Error: Can't resolve './components/CldVideo/CldPoster' in 'E:\Other\Project\Yeti\FILMD\Source\FILMD-Engine\FILMD.Web\node_modules\cloudinary-vue\src'
 @ ./node_modules/cloudinary-vue/src/index.js 5:0-56 10:134-143 14:0-18:2
 @ ./scripts/index.js
 @ multi ./scripts/index.js
ERROR in ./node_modules/cloudinary-vue/src/index.js
Module not found: Error: Can't resolve './components/CldVideo/CldVideo' in 'E:\Other\Project\Yeti\FILMD\Source\FILMD-Engine\FILMD.Web\node_modules\cloudinary-vue\src'
 @ ./node_modules/cloudinary-vue/src/index.js 4:0-54 10:105-113 14:0-18:2
 @ ./scripts/index.js
 @ multi ./scripts/index.js

**Comment by shrestha2lt8** [comment]
And below is my webpack.config.js

const VueLoaderPlugin = require('vue-loader/lib/plugin')
module.exports = {
    entry: {
        // This index.js is main file which should include all other modules 
        app: ['./scripts/index.js']
    },
    output: {
        // this says : Compiled file goes to [name].js ie. app.js in my case
        path: __dirname + "/wwwroot/js/dist/",
        filename: '[name].js'
    },
    devtool: 'source-map',
    module: {
        // modules contains Special compilation rules 
        rules: [
            {   // Ask webpack to check: If this file ends with .js, then apply some transforms
                test: /\.js$/,
                // don't transform node_modules folder  this folder need not to be compiled and not needed at production mode
                exclude: /node_modules/,
                // load this .js file using babel loader so as to make it compactible with any browser
                loader: 'babel-loader'
            },
            {
                test: /\.vue$/,
                loader: 'vue-loader'
            },
            { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' },
            {
                // Ask webpack to check: If this file ends with .css, then apply some transforms 
                test: /\.css$/,
                use: [ //  use css loader to load css file
                    { loader: "css-loader" }
                ]
            }
        ]
    },
    plugins: [
        // make sure to include the plugin!
        new VueLoaderPlugin()
    ]
};

**Comment by patrick-tolosa** [comment]
Hey @shrestha2lt8 

The SDK assumes (maybe wrongfully), that you have the extension .vue set up as a valid extension.

This is normally done in vue-CLI automatically, but if you're using a custom build you'll need to add the resolve object to your Webpack config


module.exports = {
// ...
  resolve: {
    extensions: ['.js', '.vue', '.json']
  }
/...
}

**Comment by shrestha2lt8** [comment]
Hi @patrick-tolosa ,

Awesome. It worked.

Thanks for the help.

**Comment by patrick-tolosa** [comment]
Happy to help,
In any case version 1.0.1 was released today which also solves this problem, so if you don't want to change your configuration, you can try installing the new version.

Closing this issue for now.
