### ISSUE TITLE
Can we bind publicId  with vue js variable?

### ISSUE THREAD

**Issue by shrestha2lt8** [cloudinary/cloudinary-vue#67]
On the below code. I want to bind the public-id attribute by vue js data variable.

```
 <cld-image public-id="q68mklsxqn5eqx6mg59p">
       <cld-transformation gravity="face" height="300" quality="auto:eco" width="225" crop="fill" />
 </cld-image>
```

When I use v-bind like below to give dynamic public id then the transformation does not work.

```
 <cld-image v-bind:public-id="imgPublicId">
       <cld-transformation gravity="face" height="300" quality="auto:eco" width="225" crop="fill" />
 </cld-image>
```

Could you let me know whether it is possible or not to give dynamic public-id on cld-image?

**Comment by mayashavin** [comment]
@shrestha2lt8 Thank you for reporting it. I tried your code and it works on my side. Here is the sample codeSandbox I used: https://codesandbox.io/s/cloudinary-vue-demo-flgdt
Can you please provide more details (code sample)?

**Comment by patrick-tolosa** [comment]
@shrestha2lt8  - I'm closing this issue due to time passed,
Maya has provided a working example to your question, but if you feel something doesn't work the way it should please feel free to reopen with an example
