### ISSUE TITLE
Update dependency cloudinary-video-player to 1.3

### ISSUE THREAD

**Issue by GauthierPLM** [cloudinary/cloudinary-vue#69]
The current version requested by the package is ^1.1.1, which is a quite old version and rely on many deprecated dependencies.

Using version ^1.3.2 would fix many of these dependencies.

**Comment by patrick-tolosa** [comment]
Hey @GauthierPLM, Thanks for bringing this up.

We're currently reviewing our current dependencies and are considering such upgrades.

Do you need this update for something specific, or is it just to help us maintain the project by removing deprecated dependencies?

**Comment by GauthierPLM** [comment]
I don't **need** it right now, but adding it to a project displays many warning about unmaintained and deprecated dependencies, all of them (except core-js) coming from  cloudinary-video-player.

It was to point this out and help you to ensure this package is up to date that I made the issue.

```
warning cloudinary-vue > cloudinary-video-player > videojs-contextmenu@1.2.2: This package is deprecated and unmaintained. We recommend no longer using this package. Users of videojs-contextmenu-ui should update to v5.0.0 or newer.
warning cloudinary-vue > cloudinary-video-player > videojs-ima > cryptiles@4.1.3: This module has moved and is now available at @hapi/cryptiles. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning cloudinary-vue > cloudinary-video-player > videojs-contextmenu > video.js > tsml@1.0.1: no longer maintained
warning cloudinary-vue > cloudinary-video-player > videojs-ima > cryptiles > boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning cloudinary-vue > cloudinary-video-player > videojs-ima > cryptiles > boom > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning cloudinary-vue > cloudinary-video-player > videojs-contextmenu > video.js > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

**Comment by patrick-tolosa** [comment]
Very much appreciated!
We'll include it in our roadmap to either remove or update this dependency.

**Comment by mayashavin** [comment]
We removed this dependency since it is redundant as the sdk doesn't use it. The new version will be shipped with cloudinary-video-player,
