### ISSUE TITLE
warning cloudinary-vue > core-js@2.6.9: core-js@<3 is no longer maintained and not recommended for usage

### ISSUE THREAD

**Issue by kinsaz** [cloudinary/cloudinary-vue#78]
using     "cloudinary-vue": "^1.0.1",

Gettng this message when I run npm

warning cloudinary-vue > core-js@2.6.9: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

**Comment by patrick-tolosa** [comment]
Thanks @kinsaz for the report,

This is a known issue that we plan to resolve in the near future.
In the meantime, there's no functional limitation in using the older core version.

**Comment by patrick-tolosa** [comment]
I'm closing this issue as it'll be taken internally and considered in our roadmap.
Until resolved, If you find any limitation of functionality please open a separate issue.
