### ISSUE TITLE
Error - These relative modules were not found

### ISSUE THREAD

**Issue by willdante** [cloudinary/cloudinary-vue#8]
Hi,

I've installed cloudinary-vue in Gridsome and can't compile because of this error:

`
ERROR  Failed to compile with 4 errors                                                                   
These relative modules were not found:

* ./CldImage.vue?vue&type=style&index=0&lang=scss& in ./node_modules/cloudinary-vue/src/components/CldImage.vue
* ./CldVideo.vue?vue&type=style&index=0&lang=scss& in ./node_modules/cloudinary-vue/src/components/CldVideo.vue
* ./CldPoster.vue?vue&type=style&index=0&lang=scss& in ./node_modules/cloudinary-vue/src/components/CldPoster.vue
* ./CldTransformation.vue?vue&type=style&index=0&lang=scss& in ./node_modules/cloudinary-vue/src/components/CldTransformation.vue
`

If I follow the links, like for example ./node_modules/cloudinary-vue/src/components/CldImage.vue, it works and I can see the file.

Here is my main.js setup:

`
import DefaultLayout from "~/layouts/Default.vue";
import { Cloudinary } from "cloudinary-vue";

import "cloudinary-vue/dist/Cloudinary.css";

export default function(Vue, { router, head, isClient }) {
  // Set default layout as a global component
  Vue.component("Layout", DefaultLayout);

  Vue.use(Cloudinary, {
    configuration: { cloudName: "demo" },
    components: ["CldImage"]
  });
}
`

What can be wrong here ?

Thanks in advance

**Comment by arturkulig** [comment]
Thank you for posting this issue.

I've setup a basic project with Gridsome and what allowed me to continue to work with it was to install two more dependencies. Try running this in terminal:

```
npm i -D sass-loader node-sass
```

and let me know if that worked for you.

**Comment by willdante** [comment]
Thank you, that worked !

**Comment by arturkulig** [comment]
Awesome 🎉

**Comment by billsomen** [comment]
Not working for me

**Comment by brian-cloudinary** [comment]
Hi @billsomen, could you share what exactly does not work, along with the errors you see?

**Comment by macguirerintoul** [comment]
I had the same issue. What fixed it for me was importing individual components on new lines. My environment: Gridsome `0.7.9`, cloudinary-vue `1.0.0-beta2` and `1.0.0-beta3`

**Works**
```
import CldImage from 'cloudinary-vue'
import CldTransformation from 'cloudinary-vue'
```

**Doesn't work**
```
import { CldImage, CldTransformation } from 'cloudinary-vue'
```

Any ideas why?
