### ISSUE TITLE
Nuxt error: "Unknown cloud_name"

### ISSUE THREAD

**Issue by nomadoda** [cloudinary/cloudinary-vue#80]
Re-opening [issue](https://www.google.com/search?q=cloudinary+vue+nuxt&oq=cloudinary+vue+nuxt&aqs=chrome.0.69i59j69i60.1870j0j7&sourceid=chrome&ie=UTF-8), having same problem.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross-browser issues
[ ] UI/Performance - Display or performance issues
[x] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behavior
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce

1. Use plugin:

```
// ~/plugins/cloudinary.js
import Vue from 'vue'
import Cloudinary from 'cloudinary-vue'

Vue.use(Cloudinary, {
  configuration: {
    cloudName: 'demo',
  }
})
```

2. Import cloudinary in component:

```
// ~/pages/index.vue
<template>
  <main>
    <h1>Cloudinary Test</h1>
    <cld-image publicId="sample" />
  </main>
</template>

<script>
import { CldImage } from 'cloudinary-vue';

export default {
  components: {
    CldImage,
  }
}
</script>
```

3. Console error: `Unknown cloud_name `

**It only seems to error when importing the cloudinary components in your component**

**This works:**

```
// ~/pages/index.vue
<template>
  <main>
    <h1>Cloudinary Test</h1>
    <cld-image publicId="sample" />
  </main>
</template>

<script>
export default {
}
</script>
```

## Browsers (if issue relates to UI, else ignore)
[x] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[ ] All

**Comment by DerekAlanGilbert** [comment]
Im not sure if this helps, but this is how we are setting it up w/ nuxt and it seems to be working.

``` 
// plugins/cloudinary.js
import Vue from 'vue'
import Cloudinary, { CldImage, CldTransformation } from 'cloudinary-vue'

Vue.use(Cloudinary, {
  configuration: {
    cloudName: process.env.CLOUDINARY_NAME,
    secure: true,
    privateCdn: true,
    secureDistribution: `${process.env.CLOUDINARY_DISTRIBUTION}/${process.env.CLOUDINARY_NAME}/`
  },

  components: {
    'cloudfront-transformation': CldTransformation,
    'cloudfront-image': CldImage
  }
})
```

Then we reference the component from any file like this
```
    <cloudfront-image :public-id="id" alt="some alt">
          <cloudfront-transformation
            height="576"
            width="1024"
            crop="fill"
            quality="auto:best"
            dpr="auto"
            fetch_format="auto"
          />
      </cloudfront-image>
```

hope that helps!

**Comment by patrick-tolosa** [comment]
I'm closing this issue due to time passed, please reopen if this is still occuring
