### ISSUE TITLE
CldPlaceholder missing from Exports

### ISSUE THREAD

**Issue by alexbbt** [cloudinary/cloudinary-vue#81]
## Describe the bug in a sentence or two.
CldPlaceholder is missing from the exports in this file https://github.com/cloudinary/cloudinary-vue/blob/master/src/index.js
This makes it so we cannot import that component, and must instead install the library using `Vue.use`.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross-browser issues
[ ] UI/Performance - Display or performance issues
[X] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behavior
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
View the file.

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[X] All

## Versions and Libraries (fill in the version numbers)
Vue Cloudinary SDK - 1.1.0

**Comment by patrick-tolosa** [comment]
Thanks @alexbbt for the detailed report.

We've just released version 1.1.1 to address this issue,
Please let us know if that resolves it for you.
Thanks again,
Patrick

**Comment by patrick-tolosa** [comment]
We're closing this issue as the new version should resolve the issue.
If the problem persists please reopen.

**Comment by alexbbt** [comment]
That looks like it fixed it! Thanks for getting that out so quick
