### ISSUE TITLE
Cannot play video with cld-video in Safari

### ISSUE THREAD

**Issue by pastdevr** [cloudinary/cloudinary-vue#9]
I'm getting the following error when trying to play video in Safari.
> IndexSizeError: The index is not in the allowed range.

I can see poster uploaded successfully. Example of code
```
<cld-video :id="cloudinaryPublicId" :publicId="cloudinaryPublicId" tabindex="-1"
  controls playsinline preload="metadata" @error.native="handleVideoError"
>
  <cld-transformation quality="70" video_codec="auto"></cld-transformation>
</cld-video>
```

**Comment by arturkulig** [comment]
I've tried something similar with our resource and could not replicate your issue:
https://codesandbox.io/s/yp8r1koqyv
Does that happen for you in this sample?

ℹ️ BTW Try `videoCodec` instead of `video_codec`

**Comment by pastdevr** [comment]
@arturkulig the video you placed `codesandbox` is playing fine.
After further investigation, I found that service worker might be involved in the problem which breaks range request to the video source and prevents from playing in Safari. So it might be not a problem of this component.

**Comment by arturkulig** [comment]
I'm relieved to know that and glad you were able to start to deal with your issue. Please, open new issue, in case of other problems :)
