### ISSUE TITLE
cld-placeholder loads unresponsive image in responsive cld-image

### ISSUE THREAD

**Issue by KazakovKirill** [cloudinary/cloudinary-vue#99]
**CldPlaceholder** inside **CldImage** with **responsive="fill"** loads huge original full-sized blurred picture instead of small cropped one:

_Browser requests:_
**CldImage:**
Cropped "responsive" hi-res image, which is ok:
`https://res.cloudinary.com/mycloud/image/upload/g_auto/c_fill,dpr_3.0000001192092896,h_865,w_400/dpr_auto,q_auto/v1/loremipsum/dolar.jpg`

**CldPlaceholder:**
This is huge 5000 x 5000 pixels original image, but blurred:
`https://res.cloudinary.com/mycloud/image/upload/g_auto/e_blur:2000,f_auto,q_1/dpr_auto,q_auto/v1/loremipsum/dolar.jpg`

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross-browser issues
[ ] UI/Performance - Display or performance issues
[x] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behavior
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
```
<cld-image
        public-id="loremipsum/dolar.jpg"
        fetch-format="auto"
        responsive="fill"
        quality="auto"
        height="auto"
        width="auto"
        dpr="auto"
      >
            <cld-transformation gravity="auto" />
            <cld-placeholder type="blur" />
</cld-image>
```

## Versions and Libraries
Vue Cloudinary SDK - 1.1.1
Vue - 2.6.11

**Comment by patrick-tolosa** [comment]
Hey @KazakovKirill 

Thanks for bringing this up to our attention.
We're investigating the issue and we'll update once we have more information

**Comment by themarcba** [comment]
`CldPlaceholder.vue` uses `getImageWidth` and `getImageHeight` to generate the placeholder URL.
However, these are only populated by:
```html
<cld-image width="XYZ">
```

I am not that deep into the project yet. But it seems like the solution is one of two options:
- Update `transformOptions.width` in `CldImage.vue` when resizing with the correct breakpoint
- Get the resize breakpoint in `CldPlaceholder.vue`

Again, I just started looking at the project while trying to fix it, but I don't know enough about it yet to do something. Maybe this helps someone to fix it though :)
